export const CATEGORIES = [
  { id: 'all', name: '全部', icon: '🍽️' },
  { id: 'mains', name: '主食', icon: '🍚' },
  { id: 'sides', name: '小食', icon: '🍟' },
  { id: 'drinks', name: '飲品', icon: '☕' },
  { id: 'desserts', name: '甜品', icon: '🍰' },
];

export const DEFAULT_MENU = [
  {
    id: 'item_001',
    name: '日式咖喱飯',
    description: '自家製濃厚咖喱，配白飯及溫泉蛋',
    price: 68,
    category: 'mains',
    tags: ['人氣', '推薦'],
    image: '',
    available: true,
  },
  {
    id: 'item_002',
    name: '意式番茄肉醬意粉',
    description: '新鮮番茄熬製肉醬，配彈牙意粉',
    price: 58,
    category: 'mains',
    tags: [],
    image: '',
    available: true,
  },
  {
    id: 'item_003',
    name: '香煎三文魚定食',
    description: '挪威三文魚香煎至金黃，附味噌湯及漬物',
    price: 88,
    category: 'mains',
    tags: ['推薦'],
    image: '',
    available: true,
  },
  {
    id: 'item_004',
    name: '慢煮牛肋定食',
    description: '低溫慢煮12小時，肉質嫩滑入口即化',
    price: 98,
    category: 'mains',
    tags: ['限定'],
    image: '',
    available: true,
  },
  {
    id: 'item_005',
    name: '松露薯條',
    description: '脆炸薯條配松露油及帕爾馬乾酪',
    price: 38,
    category: 'sides',
    tags: ['人氣'],
    image: '',
    available: true,
  },
  {
    id: 'item_006',
    name: '唐揚雞塊',
    description: '日式炸雞塊，配蛋黃醬及檸檬',
    price: 42,
    category: 'sides',
    tags: [],
    image: '',
    available: true,
  },
  {
    id: 'item_007',
    name: '煙燻三文魚沙律',
    description: '新鮮沙律配煙燻三文魚及油醋汁',
    price: 48,
    category: 'sides',
    tags: ['推薦'],
    image: '',
    available: true,
  },
  {
    id: 'item_008',
    name: '手打咖啡',
    description: '自家烘焙咖啡豆，手沖萃取',
    price: 32,
    category: 'drinks',
    tags: [],
    image: '',
    available: true,
  },
  {
    id: 'item_009',
    name: '抹茶拿鐵',
    description: '日本宇治抹茶，配燕麥奶',
    price: 35,
    category: 'drinks',
    tags: ['推薦'],
    image: '',
    available: true,
  },
  {
    id: 'item_010',
    name: '鮮榨果汁',
    description: '每日新鮮現榨，可選橙/蘋果/混合',
    price: 28,
    category: 'drinks',
    tags: [],
    image: '',
    available: true,
  },
  {
    id: 'item_011',
    name: '伯爵茶',
    description: '斯里蘭卡產伯爵紅茶，可回沖',
    price: 25,
    category: 'drinks',
    tags: [],
    image: '',
    available: true,
  },
  {
    id: 'item_012',
    name: '焦糖布丁',
    description: '法式手法製作，表面焦糖微苦帶甜',
    price: 28,
    category: 'desserts',
    tags: ['人氣'],
    image: '',
    available: true,
  },
  {
    id: 'item_013',
    name: '抹茶 tiramisu',
    description: '以抹茶代替咖啡的意式經典甜品',
    price: 38,
    category: 'desserts',
    tags: ['推薦'],
    image: '',
    available: true,
  },
  {
    id: 'item_014',
    name: '時令水果拼盤',
    description: '精選當季新鮮水果',
    price: 32,
    category: 'desserts',
    tags: [],
    image: '',
    available: true,
  },
];

export const ORDER_STATUSES = {
  pending: { label: '待處理', color: 'warning', icon: '⏳' },
  preparing: { label: '製作中', color: 'info', icon: '👨‍🍳' },
  ready: { label: '可取餐', color: 'success', icon: '✅' },
  completed: { label: '已完成', color: 'neutral', icon: '✔️' },
};

export const MOCK_ORDERS = [
  {
    id: 'ORD-001',
    customerName: '陳先生',
    tableNumber: '5',
    pickupTime: '12:30',
    notes: '少辣',
    items: [
      { ...DEFAULT_MENU[0], quantity: 2 },
      { ...DEFAULT_MENU[4], quantity: 1 },
    ],
    subtotal: 174,
    serviceCharge: 17.4,
    total: 191.4,
    status: 'pending',
    createdAt: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'ORD-002',
    customerName: '李小姐',
    tableNumber: '外帶',
    pickupTime: '13:00',
    notes: '',
    items: [
      { ...DEFAULT_MENU[2], quantity: 1 },
      { ...DEFAULT_MENU[8], quantity: 2 },
    ],
    subtotal: 158,
    serviceCharge: 15.8,
    total: 173.8,
    status: 'preparing',
    createdAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'ORD-003',
    customerName: '王生',
    tableNumber: '3',
    pickupTime: '11:45',
    notes: '加蛋',
    items: [
      { ...DEFAULT_MENU[1], quantity: 1 },
      { ...DEFAULT_MENU[5], quantity: 2 },
    ],
    subtotal: 142,
    serviceCharge: 14.2,
    total: 156.2,
    status: 'completed',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
];
